# Generated by Django 4.2.3 on 2023-08-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='cutting_boards',
            field=models.ManyToManyField(blank=True, to='main_app.cuttingboard'),
        ),
        migrations.AlterField(
            model_name='cuttingboard',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
