# Generated by Django 4.2.3 on 2023-08-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('prep_time', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('optional_link', models.URLField(blank=True)),
                ('upload_file', models.FileField(blank=True, upload_to='recipe_uploads/')),
                ('checkboxes', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
